@startuml
class Backgammon{}

class Board{}

class OffBoard{}


class Point {}

class Piece{}

enum Color{
  RED
  BLACK
}

class Goal{}

class Bar{}

class MatchPlay{}

class Turn{}

class Player{}

class Dice{}

class DoblingCube{}

class Match{}

class Gammon{}

class BackGammon{}

class Score{}

class Action {}
class RollDice {}
class MovePiece {}
class Bet {}
class BetAccept {}
class BetReject {}

class Sense{}
note top: invert point number

Player --> Score
Score ..> MatchPlay
MatchPlay --> Goal
Match -up-|> Score
Gammon -up-|> Score
BackGammon -up-|> Score
Backgammon *--> MatchPlay
Backgammon *--> Board
Backgammon *--> Turn
Player o--> DoblingCube
Turn *--> "2" Player
Backgammon *--> "2" Player
Board *--> "4x6" Point
Board *--> Bar
Board *--> OffBoard
Player *--> Color
Piece *--> Color
Point --> Point

Board *--> Sense
Sense *--> Color
Point ..> Sense

OffBoard o--> "0..29" Piece
Bar o--> "0..15" Piece
Point o--> "0..15" Piece

Player *--> "2" Dice
Player o--> Goal
Player ..> Action

Action <|-- RollDice
Action <|-- MovePiece
Action <|-- Bet
Action <|-- BetAccept
Action <|-- BetReject
@enduml
