@startuml contexto

state INITIAL
state PENDING_MOVE
state ABLE_BET
state DISABLE_BET
state REQUESTED_BET
state EXIT

state is_endmatch <<choice>>
state is_possible_moves <<choice>>
state can_bet <<choice>>
state is_possible_moves2 <<choice>>
state accept_bet <<choice>>

[*] -down-> INITIAL
INITIAL --> PENDING_MOVE: Start
INITIAL --> EXIT: Exit

PENDING_MOVE --> is_possible_moves : MovePiece

is_possible_moves --> PENDING_MOVE : [is_possible_moves]
is_possible_moves --> is_endmatch

is_endmatch --> INITIAL : [is_endmatch]
is_endmatch --> can_bet

can_bet --> ABLE_BET : [can_bet]
can_bet --> DISABLE_BET

PENDING_MOVE --> EXIT : Exit
ABLE_BET --> EXIT : Exit
DISABLE_BET --> EXIT : Exit

ABLE_BET --> is_possible_moves2 : RollDice
DISABLE_BET --> is_possible_moves2 : RollDice

is_possible_moves2 --> PENDING_MOVE : [is_possible_moves]
is_possible_moves2 --> can_bet

ABLE_BET --> REQUESTED_BET : RequestBet
REQUESTED_BET --> accept_bet : ResponseBet
accept_bet --> DISABLE_BET : [yes]
accept_bet --> is_endmatch

EXIT --> [*]
@enduml
