@startuml contexto

state INITIAL
state PENDING_MOVE
state INITIAL_TURN_ABLE_BET
state ANSWER_BET
state INITIAL_TURN_DISABLE_BET
state EXIT

state s2 <<choice>>
state s3 <<choice>>


[*] --> INITIAL
INITIAL --> PENDING_MOVE: Start
INITIAL --> EXIT: Exit

PENDING_MOVE --> s2 : MovePiece
s2 --> INITIAL_TURN_ABLE_BET : [is_not_possible_moves and is_can_bet]
s2 --> INITIAL_TURN_DISABLE_BET : [is_not_possible_moves and is_not_can_bet]
s2 --> PENDING_MOVE : [is_possible_moves]
PENDING_MOVE --> EXIT : Exit
INITIAL_TURN_ABLE_BET --> EXIT : Exit
INITIAL_TURN_DISABLE_BET --> EXIT : Exit

INITIAL_TURN_ABLE_BET --> s2 : RollDice
INITIAL_TURN_DISABLE_BET --> s2 : RollDice

INITIAL_TURN_ABLE_BET --> ANSWER_BET : Bet
ANSWER_BET --> INITIAL_TURN_DISABLE_BET : AcceptBet
ANSWER_BET --> s3 : RejectBet
s3 --> PENDING_MOVE : [is_endgame]
s3 --> INITIAL : [is_endmatch]

EXIT --> [*]
@enduml
