@startuml contexto

state INITIAL : \
""### BACKGAMMON ###""\n\
""Each player should choose a color.""\n\
""Define your goal? (1-64):""

state IN_GAME : \
""|- - - - - - - - - - - - - - - - - - - - - - - - - - - - |""\n\
""|  13  14  15  16  17  18 |    |  19  20  21  22  23  24 |""\n\
""|  5●             3○     |    |  5○                 2●|""\n\
""|                         | 0○|                         |""\n\
""|                         | BAR|                         |""\n\
""|                         | 0●|                         |""\n\
""|  5○             3●     |    |  5●                 2○|""\n\
""|  12  11  10   9   8   7 |    |   6   5   4   3   2   1 |""\n\
""|- - - - - - - - - - - - - - - - - - - - - - - - - - - - |""\n\
""1) Move from point 24 to 23 (dice 1)""\n\
""2) Move from point 24 to 22 (dice 2)""\n\
""3) ...""\n\
""4) Roll""\n\
""5) Bet""\n\
""6) Exit""

state END_GAME : \
""### BACKGAMMON ###""\n\
""1) Resume""\n\
""2) Exit""

state EXIT : \
""### BACKGAMMON ###""\n\
""###            ###""\n\
""###     BYE    ###""\n\
""###            ###""\n\
""##################""

state is_endgame <<choice>>
state is_resume <<choice>>
state exit_from_initial <<choice>>


[*] --> INITIAL
INITIAL --> exit_from_initial: Start
exit_from_initial --> IN_GAME
exit_from_initial --> EXIT: [exit]

IN_GAME --> IN_GAME : RollDice
IN_GAME --> IN_GAME : Bet
IN_GAME --> is_endgame: MovePiece
IN_GAME --> EXIT: Exit
is_endgame --> IN_GAME
is_endgame --> END_GAME: [is_endgame]


END_GAME --> is_resume: Resume

is_resume --> INITIAL: [yes]
is_resume --> EXIT

EXIT --> [*]
@enduml
