@startuml
title MVP-PV

package Models {
    class Match {
        games: list[Game]
        goal: Goal
        turn: Turn

    }
    class Game {
        board: Board

        is_endgame() -> bool
        type_endgame() -> EndGame
    }

    class Board {
        positions: list[Position]

        is_all_piece_last_square(color: Color) -> bool
        is_any_pieces_in_bar(color: Color) -> bool
        is_all_pieces_off_board(color: Color) -> bool
        is_any_piece_off_board(color: Color) -> bool
        is_any_piece_at_first_square(color: Color) -> bool
        move_piece(position: Position, position: Position, color: Color)
        reset()
    }

    class DoublingCube {
        value: int  # 2^1 .. 2^6
    }

    class Player {
        last_roll: list[Dice]
        last_moves: list[Move]
        score: int
        doubling_cube: bool = False

        roll(times: int)
        can_bet() -> bool
        bet()
        accept_bet()
        reject_bet()
        is_winner()
        earn_score(score: int)
    }

    class Dice {
        value: int  # between 1..6
        __init__()  # constructor
    }

    class Turn {
        current_player: Player = None
        get_next_player(default=None): Player
    }
}

package Controllers {
    class ConfigureMatch {
        configure()
    }
    class PlayMatch {
        initialize_game()
    }
    class PlayGame {
        select_menu()
    }
    class RollDice
    class MovePiece
    class Bet

    PlayGame --> RollDice
    PlayGame --> MovePiece
    PlayGame --> Bet
}

package Views {
    class EndGameView {
        show()
    }

    class MenuView {
        show()
        read()
    }

    class ConfigurationMatchPlayView {
        show()
        read()  # read input
    }

    class BoardView {
        show(color: Color)
    }

    class DiceView {
        show()
    }

    class BetView {
        show()
        read()
    }

    class PlayerView {
        show()
    }

    MenuView --> BoardView
    MenuView --> PlayerView
    MenuView --> DiceView
    MenuView --> BetView
}

package Types {
    enum Color {
        RED
        BLACK
    }

    enum Point {
        1..24
    }
}

@enduml
