@startuml

package Views {
    boundary MatchView
    boundary PlayerView
    boundary GameView
    boundary GoalView
    boundary MenuView
    boundary BoardView
    boundary ActionView
    boundary PositionView
    boundary PieceView
    boundary DoublingCubeView

    MatchView *--> GameView
    MatchView *--> GoalView
    MatchView *--> PlayerView
    GameView *--> MenuView
    GameView *--> BoardView
    GameView *--> DoublingCubeView
    MenuView *--> ActionView
    BoardView *--> PositionView
    PositionView *--> PieceView
}

package Models {
    entity Match
    entity Player
    entity Game
    entity Goal
    entity Board
    entity Position
    entity Piece
    entity DoublingCube

    Match *-down-> Player
    Match *-down-> Goal
    Match *-down-> Game
    Game *-down-> DoublingCube
    Game *-down-> Board
    Board *-down-> Position
    Position *-down-> Piece
}

package Controllers {
    control StartController
    control DoActionController
    control SelectResumeController
    control ExitController

    StartController ..> DoActionController
    StartController ..> ExitController
    DoActionController ..> DoActionController
    DoActionController ..> SelectResumeController
    DoActionController ..> ExitController
    SelectResumeController ..> StartController
    SelectResumeController ..> ExitController
}

Views -down-> Controllers

Controllers -down-> Models

@enduml
