@startuml
hide empty description

state INITIAL
state PENDING_MOVE
state ABLE_BET
state DISABLE_BET
state EXIT

state " " as 1

INITIAL -[#green]-> 1
note on link #white
    <b>Player request to</b>
    * Exit
end note

PENDING_MOVE -[#green]-> 1
note on link #white
    <b>Player request to</b>
    * Exit
end note

ABLE_BET -[#green]-> 1
note on link #white
    <b>Player request to</b>
    * Exit
end note

DISABLE_BET -[#green]-> 1
note on link #white
    <b>Player request to</b>
    * Exit
end note

1 -[#green]-> EXIT
note on link #white
    <b>System shows</b>
    * exit message
end note
