@startuml

state STARTED
state DICE_ROLLED
state BET
state BET2 as "BET"
state MOVED_PIECE

state MENU ##green {
    state " " as 1
    state " " as 2

    [*] -[#green]-> 1
    1 -[#green]-> 2
    note on link #white
        <b>System requires</b>
        * Select menu option
        <b>System allows</b>
        * rollDice
        * movePiece
        * Bet
        * exit
        <b>System shows</b>
        * board
        * menu:
            - ACA IRIAN LAS REGLAS??
            - exit: active always
    end note

}


STARTED --> MENU
DICE_ROLLED --> MENU
BET --> MENU

MENU --> BET2 : Bet
MENU --> MOVED_PIECE : MovePiece
MENU --> EXIT : Exit


@enduml
