@startuml
hide empty description

state PENDING_MOVE

state " " as 1
state " " as endgame

state is_endgame <<choice>>
state is_endmatch <<choice>>
state is_possible_moves <<choice>>

1 -[#green]-> is_possible_moves
note on link #white
    <b>System shows</b>
    * player movement
end note

is_possible_moves -[#green]-> :ShowMenu : [is_possible_moves]
is_possible_moves -[#red]-> is_endgame

is_endgame -[#green]-> endgame : [is_endgame]
endgame -[#green]-> is_endmatch
note on link #white
    <b>System shows</b>
    * game result
end note
is_endgame -[#red]-> :ShowMenu
note on link #white
    <b>System shows</b>
    * player turn changed
end note

is_endmatch -[#purple]-> :ShowMenu : [is_endmatch]
note on link #white
    <b>System shows</b>
    * match result
end note
is_endmatch -[#blue]-> :ShowMenu
note on link #white
    <b>System shows</b>
    * new game started
    * player turn changed
end note

PENDING_MOVE -[#green]-> 1
note on link #white
    <b>Player request to</b>
    * MovePiece
end note
