@startuml

state IN_GAME
state IN_GAME2 as "IN_GAME"
state END_GAME

state MovePiece ##green {
    state " " as 1
    state " " as 2

    [*] -[#green]-> 1
    1 -[#green]-> 2
    note on link #white
        <b>System shows</b>
        * board
        * menu
    end note
    2 -[#green]-> [*]
    2 --> [*]

}

IN_GAME -[#green]-> MovePiece
note on link #white
    <b>Player request to</b>
    * MovePiece
end note

MovePiece -[#green]-> IN_GAME2
MovePiece -[#red]-> END_GAME