@startuml
hide empty description

state ANSWER_BET


state RejectBet ##green {
    state " " as 1
    state " " as 2

    state status <<choice>>

    [*] -[#green]-> 1
    1 -[#green]-> status
    note on link #white
        <b>System shows</b>
        * bet rejected
    end note

    status -[#green]-> 2 : [is_endgame]
    status -[#red]-> [*] : [is_endmatch]

    2 -[#green]-> [*]
    note on link #white
        <b>System </b>
        * start new game (turn is for player not started last game)
    end note
}

ANSWER_BET -[#green]-> RejectBet
note on link #white
    <b>Player request to</b>
    * RejectBet
end note

RejectBet -[#green]-> :RollDice
:RollDice -[#green]-> PENDING_MOVE
RejectBet -[#red]-> :ShowMenu
:ShowMenu -[#red]-> INITIAL

@enduml
