@startuml
hide empty description

state REQUESTED_BET
state response <<choice>>
state status <<choice>>

REQUESTED_BET -[#green]-> response
note on link #white
    <b>Player request to</b>
    * ResponseBet
end note

response -[#green]-> :ShowMenu : [accept_bet]
note on link #white
    <b>System shows</b>
    * bet accepted
    * doubling cube doubled
    * player turn
end note

response -[#red]-> status
note on link #white
    <b>System shows</b>
    * bet rejected
    * game result
end note

status -[#blue]-> :ShowMenu
note on link #white
    <b>System </b>
    * new game started
    * player turn
end note

status -[#red]-> :ShowMenu : [is_endmatch]
note on link #white
    <b>System shows</b>
    * match result
end note

:ShowMenu -[#blue]-> ABLE_BET
:ShowMenu -[#red]-> INITIAL
:ShowMenu -[#green]-> DISABLE_BET

@enduml
