@startuml

state IN_GAME
state IN_GAME2 as "IN_GAME"
state END_GAME

state ResponseBet ##green {
    state response <<choice>>
    state " " as 1

    [*] -[#green]-> 1
    1 -[#green]-> response
    note on link #white
        <b>Player Response</b>
    end note

    response -[#green]-> [*]
    note on link #white
        <b>System shows:</b>
        Doubling Cube doubled
        Accepted Bet
    end note

    response -[#red]-> [*]: No
    note on link #white
        <b>System shows</b>
        End Game
    end note
}

IN_GAME -[#green]-> ResponseBet
note on link #white
    <b>Player request to</b>
end note

ResponseBet -[#green]-> :ShowMenu
:ShowMenu -[#green]-> IN_GAME2
ResponseBet -[#red]-> END_GAME

:ShowMenu -[hidden]right-> END_GAME
