@startuml
hide empty description

state 1 as " "
state 2 as " "
state dices_equal as " " <<choice>>

:Start -[#green]-> 1
note on link #white
    <b>Controller request to</b>
    * RollDice
end note

1 -[#green]-> dices_equal
note on link #white
    <b>System shows</b>
    * red dice value
    * black dice value
end note

dices_equal -[#red]-> 1 : [dices_are_equal]

dices_equal -[#green]-> :ShowMenu : [red_dice_greater_than_black_dice]
note on link #white
    <b>System shows</b>
    * player turn to red
end note

dices_equal -[#blue]-> :ShowMenu
note on link #white
    <b>System shows</b>
    * player turn to black
end note

ABLE_BET -[#green]-> 2
note on link #white
    <b>Player request to</b>
    * RollDice
end note

DISABLE_BET -[#green]-> 2
note on link #white
    <b>Player request to</b>
    * RollDice
end note

2 -[#green]-> :ShowMenu
note on link #white
    <b>System shows</b>
    * two dices value
end note

ABLE_BET -[hidden]right-> DISABLE_BET
ABLE_BET -[hidden]right-> :Start

@enduml
