@startuml
hide empty description

state INITIAL

state " " as 1
state " " as 2

state validate <<choice>>

1 -[#green]-> 2
note on link #white
    <b>System shows</b>
    * Welcome message
    * Goal message
    <b>System requires</b>
    * goal (number between 1 and 64, both inclusive)
end note

2 -[#green]-> validate
note on link #white
    <b>Player provides</b>
    * goal
end note

validate -[#red]-> 2
note on link #white
    invalid goal
end note

validate -[#green]-> :RollDice

INITIAL -[#green]-> 1
note on link #white
    <b>Player request to</b>
    * Start
end note

:RollDice -[#green]-> PENDING_MOVE

@enduml
