@startuml use_cases
left to right direction

actor Player

usecase Start
usecase MovePiece
usecase RollDice
usecase Bet
usecase AcceptBet
usecase RejectBet
usecase Exit

usecase ShowMenu

Player --> Start
Start ..> ShowMenu : <extend>
Player --> MovePiece
MovePiece ..> ShowMenu : <extend>
Player --> Bet
Bet ..> ShowMenu : <extend>
RollDice ..> ShowMenu : <include>
Player --> AcceptBet
Player --> RejectBet
Player --> RollDice
Player --> Exit

@enduml
