@startuml use_cases
left to right direction

actor Player

usecase Start
usecase MovePiece
usecase RollDice
usecase RequestBet
usecase ResponseBet
usecase Exit
usecase ShowMenu

Player --> Start
Start ..> RollDice : <include>
Player --> MovePiece
MovePiece ..> ShowMenu : <extend>
Player --> RequestBet
RequestBet ..> ShowMenu : <extend>
RollDice ..> ShowMenu : <include>
Player --> ResponseBet
Player --> RollDice
Player --> Exit

@enduml
