@startuml

actor Player2 as "Player"

package Views {
    package Match3 as "Match"{
        boundary GameView
    }
}

package Models {
    package Match4 as "Match"{
        entity Game
    }
}

package Controllers {
    package Menu {
        control ShowMenuController
        control BetController

        BetController ..> ShowMenuController: <extend>
    }
}

Player2 -right-> BetController
BetController -right-> Game
BetController -right-> GameView

@enduml
