@startuml

package Views {
    package Menu as ViewsMenu {
        object MatchView
    }
}

package Models {
    package Board3 as "Board" {
        object Move
        object Match
    }
}

package Controllers {
    package Menu {
        object MenuController
        object MovePieceController

        MovePieceController --> MenuController
        note on link
            execute()
        end note

        MenuController --> MovePieceController
        note on link
            execute(MovePieceAction)
        end note
    }
}

MovePieceController -right-> Move
note on link
    serialize(MovePieceAction) : MoveSerialized
end note

MovePieceController -right-> Match
note on link
    move(MovePieceAction)
    possible_moves() : list[Move]
    is_endgame() : bool
    is_end() : bool
    serialize() : MatchSerialized
    serialize_last_game() : GameSerialized
    new_game()
    change_game_turn()
end note

MovePieceController --> MatchView
note on link
    show_move(MoveSerialized)
    show_game(GameSerialized)
    show(MatchSerialized)
end note

@enduml
