@startuml

package Views {
    package Menu as ViewsMenu {
        object MatchView
    }
}

package Models {
    package Board3 as "Board" {
        object Board
        object Move
        object Match
    }
}

package Controllers {
    package Menu {
        object MenuController
        object MovePieceController

        MovePieceController --> MenuController
        note on link
            execute()
        end note

        MenuController --> MovePieceController
        note on link
            execute_action(Action)
        end note
    }
}

MovePieceController -right-> Move
note on link
    from_dto(MoveSerialized) : Move
end note

MovePieceController -right-> Board
note on link
    serialize() : BoardSerialized
    move(Move)
end note

MovePieceController -right-> Match
note on link
    serialize() : MatchSerialized
    serialize_last_game() : GameSerialized
end note

MovePieceController --> MatchView
note on link
    show_move(MoveSerialized)
    show_endgame(GameSerialized)
    show_end(MatchSerialized)
    show_game_turn(GameSerialized)
end note

@enduml
