@startuml

package Models {
    package Match as "Match" {
        object Match
    }
}

package Views {
    package Match2 as "Match" {
        object MatchView
    }
}

package Controllers {
    package Menu {
        object MenuController
        object RequestBetController
    }
}

MenuController --> RequestBetController
note on link
    execute(RequestBetAction)
end note

RequestBetController --> Match
note on link
    request_bet()
end note

RequestBetController --> MatchView
note on link
    show_bet()
end note

RequestBetController --> MenuController
note on link
    execute()
end note

@enduml
