@startuml
allow_mixing

package Models {
    package Match as "Match" {
        object Match
    }
}

package Views {
    package Match2 as "Match" {
        object MatchView
    }
}

package Controllers {
    package Menu2 as "Menu" {
        object ResponseBetController
        object MenuController
    }
}

MenuController --> ResponseBetController
note on link
    execute(ResponseBetAction)
end note

ResponseBetController --> MenuController
note on link
    execute()
end note

ResponseBetController --> Match
note on link
    response_bet(ResponseBetAction)
    is_end() : bool
    serialize_game(): GameSerialized
    serialize(): MatchSerialized
end note

ResponseBetController --> MatchView
note on link
    show_response_bet(GameSerialized)
    show_game(GameSerialized)
    show(MatchSerialized)
end note

@enduml
