@startuml

package Views {
    package Match3 as "Match"{
        object MatchView
    }
}

package Controllers {
    package Menu {
        object MenuController
    }

    package Match2 as "Match" {
        object StartController
        object RollDiceController
    }
}

StartController --> RollDiceController
note on link
    execute()
end note

MenuController -down-> StartController
note on link
    execute()
end note

StartController --> MatchView
note on link
    show_title()
    interact_goal()
end note

@enduml
