@startuml
allow_mixing

actor Player

package Views {
    package Match3 as "Match"{
        object MatchView
    }
}

package Controllers {
    package Menu {
        object MenuController
        object RollDiceController
    }

    package Match2 as "Match" {
        object StartController
    }
}

StartController --> RollDiceController
note on link
    execute()
end note

MenuController -down-> StartController
note on link
    execute(StartAction)
end note

StartController --> MatchView
note on link
    show_title()
    interact_goal()
end note

Player --> MatchView
note on link
    interact()
end note

@enduml
