@startuml

package Views {
    package Match3 as "Match"{
        object GoalView
        object MatchView
    }
}

package Controllers {
    package Menu {
        object ShowMenuController
    }

    package Match2 as "Match" {
        object ExitController
        object StartController
        object RollDiceController
    }
}

StartController --> RollDiceController
note on link
    execute
end note
StartController --> StartController
note on link
    execute
end note
StartController -right-> ExitController: execute
StartController -down-> ShowMenuController: execute
StartController --> GoalView : interact
StartController --> MatchView : showTitle

@enduml
