@startuml

object ":Backgammon" as Backgammon

object ":Board" as Board

object ":Point" as Point1 {
    number = 1
}

object ":Point" as Point6 {
    number = 6
}

object ":Point" as Point8 {
    number = 8
}

object ":Point" as Point12 {
    number = 12
}

object ":Point" as Point13 {
    number = 13
}

object ":Point" as Point17 {
    number = 17
}

object ":Point" as Point19 {
    number = 19
}

object ":Point" as Point24 {
    number = 24
}

object ":Piece" as PieceB1
object ":Piece" as PieceB2
object ":Piece" as PieceB3
object ":Piece" as PieceB4
object ":Piece" as PieceR1
object ":Piece" as PieceR2
object ":Piece" as PieceR3
object ":Piece" as PieceR4

object ":Color" as ColorBlack {
    BLACK
}

object ":Color" as ColorRed {
    RED
}

Backgammon *--> Board
Board *--> Point1
Board *--> Point6
Board *--> Point8
Board *--> Point12
Board *--> Point13
Board *--> Point17
Board *--> Point19
Board *--> Point24

Point1 *--> "2" PieceR1
Point12 *--> "5" PieceR2
Point17 *--> "3" PieceR3
Point19 *--> "5" PieceR4

Point6 *--> "5" PieceB1
Point8 *--> "3" PieceB2
Point13 *--> "5" PieceB3
Point24 *--> "2" PieceB4

PieceB1 *--> ColorBlack
PieceB2 *--> ColorBlack
PieceB3 *--> ColorBlack
PieceB4 *--> ColorBlack
PieceR1 *--> ColorRed
PieceR2 *--> ColorRed
PieceR3 *--> ColorRed
PieceR4 *--> ColorRed

@enduml
