@startuml rollDice
state IN_GAME
state ROLLING_DICE
state if_is_first_roll <<choice>>
state if_is_player_red <<choice>>

[*] --> IN_GAME
IN_GAME --> if_is_first_roll: Roll
if_is_first_roll --> ROLLING_DICE: [if_is_first_roll]
if_is_first_roll --> if_is_player_red
if_is_player_red --> ROLLING_DICE: [if_is_player_red]
if_is_player_red --> ROLLING_DICE

ROLLING_DICE --> ROLLING_DICE: [if_first_roll and if_equals]
ROLLING_DICE --> IN_GAME
ROLLING_DICE --> [*]
@enduml